language: node_js
node_js:
- stable
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_8fb4cefaf9ce_key -iv $encrypted_8fb4cefaf9ce_iv -in galaxyboard.enc -out id_rsa -d
- chmod 600 id_rsa
- chmod 700 deploy.sh